import { CommonModule, DatePipe, DecimalPipe } from '@angular/common';
import { Component, Input, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  AssetComplianceRecord, AssetFuelEntry, AssetMaintenancePlan, AssetMeterReading, AssetWorkOrder,
  SENATLA_TRADING_ORGANIZATION_ID,
} from '../core/models/app.models';
import { OfficeAdminService } from '../core/services/office-admin.service';
import { AssignmentDecision, AssignmentReview } from '../core/assignment/assignment-planning';

@Component({
  selector: 'app-asset-operations', standalone: true,
  imports: [CommonModule, FormsModule, DatePipe, DecimalPipe],
  template: `
    <section class="rounded-2xl border border-gray-800 bg-gray-900 p-4">
      <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-sm font-bold uppercase tracking-wider text-gray-400">Lifecycle operations</h2><p class="mt-1 text-xs text-gray-500">Custody, compliance, meter, maintenance and return-to-service controls.</p></div><span *ngIf="asset()" class="text-xs font-bold text-yellow-400">{{ asset()!.make }} {{ asset()!.model }}</span></div>
      <div *ngIf="!asset()" class="mt-4 rounded-xl border border-dashed border-gray-700 px-4 py-8 text-center text-sm text-gray-500">Select Edit on an asset to manage its lifecycle.</div>
      <div *ngIf="asset()" class="mt-4 space-y-5">
        <div *ngIf="feedback()" class="rounded-lg border border-gray-700 bg-gray-950 px-3 py-2 text-sm text-gray-300">{{ feedback() }}</div>
        <div class="grid gap-4 xl:grid-cols-2">
          <div class="rounded-xl border border-gray-800 bg-gray-950 p-3">
            <form (ngSubmit)="reviewTransfer()"><h3 class="text-xs font-bold uppercase tracking-wider text-gray-400">Custody transfer</h3><div class="mt-3 grid gap-2 sm:grid-cols-2"><select [(ngModel)]="transferSiteId" (ngModelChange)="transferReview.set(null)" name="transferSiteId" class="min-h-11 rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><option value="">Select target site</option><option *ngFor="let site of service.activeSites()" [value]="site.id">{{ site.name }}</option></select><input [(ngModel)]="transferCustodian" name="transferCustodian" placeholder="New custodian" class="min-h-11 rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><input [(ngModel)]="transferNotes" name="transferNotes" placeholder="Private handover notes" class="min-h-11 rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm sm:col-span-2"><button [disabled]="!transferSiteId" class="min-h-11 rounded border border-yellow-700 px-3 py-2 text-xs font-bold uppercase text-yellow-200 disabled:opacity-40 sm:col-span-2">Review transfer</button></div></form>
            <section *ngIf="transferReview() as review" aria-live="polite" class="mt-3 rounded-lg border border-gray-700 p-3"><div class="flex justify-between gap-2"><strong class="text-sm text-white">{{ review.outcome | titlecase }}</strong><span class="text-xs uppercase text-gray-400">{{ review.items[0]?.roleOrClass }}</span></div><div *ngFor="let reason of review.items[0]?.reasons" class="mt-2 text-xs"><p class="font-semibold text-amber-200">{{ reason.message }}</p><p class="mt-1 text-gray-500">{{ reason.action }}</p></div><div *ngIf="review.items[0]?.alternatives.length" class="mt-3"><p class="text-[10px] font-bold uppercase tracking-wider text-gray-500">Ranked eligible alternatives</p><p *ngFor="let alternative of review.items[0]?.alternatives" class="mt-2 rounded border border-gray-800 px-2 py-2 text-xs"><span class="font-semibold text-white">{{ alternative.label }}</span><span class="ml-2 text-gray-500">{{ alternative.score }} points - {{ alternative.scoreReasons.join(', ') }}</span></p></div><label class="mt-3 block text-[10px] font-bold uppercase tracking-wider text-gray-500">Controlled decision reason<select [ngModel]="transferReasonCode()" (ngModelChange)="transferReasonCode.set($event)" class="mt-1 min-h-11 w-full rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><option value="">Select when rejecting or overriding</option><optgroup label="Reject"><option value="assignment_deferred">Transfer deferred</option><option value="alternative_not_suitable">Alternative not suitable</option><option value="additional_evidence_required">Additional evidence required</option></optgroup><optgroup label="Override warning"><option value="maintenance_plan_confirmed">Maintenance plan confirmed</option><option value="operational_continuity">Operational continuity</option><option value="manager_authorized">Manager authorised</option></optgroup></select></label><div class="mt-3 grid gap-2"><button *ngIf="review.outcome === 'ready'" type="button" (click)="transfer('accept')" class="min-h-11 rounded bg-emerald-500 px-3 py-2 text-xs font-bold uppercase text-black">Accept transfer</button><button *ngIf="review.outcome === 'warning'" type="button" (click)="transfer('override')" [disabled]="!transferReasonCode()" class="min-h-11 rounded bg-amber-400 px-3 py-2 text-xs font-bold uppercase text-black disabled:opacity-40">Override warning</button><button type="button" (click)="transfer('reject')" [disabled]="!transferReasonCode()" class="min-h-11 rounded border border-red-800 px-3 py-2 text-xs font-bold uppercase text-red-300 disabled:opacity-40">Reject suggestion</button></div></section>
          </div>
          <form (ngSubmit)="saveCompliance()" class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase tracking-wider text-gray-400">Compliance record</h3><div class="mt-3 grid gap-2 sm:grid-cols-2"><select [(ngModel)]="compliance.complianceType" name="complianceType" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><option value="licence">Licence</option><option value="roadworthy">Roadworthy</option><option value="insurance">Insurance</option><option value="inspection">Inspection</option><option value="certification">Certification</option><option value="warranty">Warranty</option><option value="other">Other</option></select><input [(ngModel)]="compliance.referenceNumber" name="referenceNumber" placeholder="Reference" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><label class="text-[10px] text-gray-500">Expiry<input [(ngModel)]="compliance.expiresAt" name="expiresAt" type="date" class="mt-1 w-full rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm text-white"></label><input [(ngModel)]="compliance.documentPath" name="documentPath" placeholder="Private evidence path" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><button class="rounded bg-blue-500 px-3 py-2 text-xs font-bold text-white sm:col-span-2">Save compliance</button></div></form>
          <form (ngSubmit)="recordMeter()" class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase tracking-wider text-gray-400">Meter reading</h3><div class="mt-3 grid gap-2 sm:grid-cols-2"><select [(ngModel)]="meter.meterType" name="meterType" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><option value="odometer_km">Odometer (km)</option><option value="engine_hours">Engine hours</option><option value="cycles">Cycles</option></select><input [(ngModel)]="meter.reading" name="reading" type="number" min="0" step="0.1" placeholder="Reading" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><button class="rounded bg-blue-500 px-3 py-2 text-xs font-bold text-white sm:col-span-2">Record meter</button></div></form><form (ngSubmit)="saveFuel()" class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase tracking-wider text-gray-400">Fuel & cost</h3><div class="mt-3 grid gap-2 sm:grid-cols-2"><input [(ngModel)]="fuel.fuelDate" name="fuelDate" type="date" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><input [(ngModel)]="fuel.litres" name="fuelLitres" type="number" min="0.01" step="0.01" placeholder="Litres" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><input [(ngModel)]="fuel.unitCost" name="fuelUnitCost" type="number" min="0" step="0.01" placeholder="Cost per litre" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><input [(ngModel)]="fuel.supplier" name="fuelSupplier" placeholder="Supplier" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><input [(ngModel)]="fuel.referenceNumber" name="fuelReference" placeholder="Receipt / reference" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><input [(ngModel)]="fuel.odometerKm" name="fuelOdometer" type="number" min="0" placeholder="Odometer km" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><button class="rounded bg-blue-500 px-3 py-2 text-xs font-bold text-white sm:col-span-2">Record fuel expense</button></div></form>
          <form (ngSubmit)="saveWorkOrder()" class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase tracking-wider text-gray-400">Work order</h3><div class="mt-3 grid gap-2 sm:grid-cols-2"><input [(ngModel)]="workOrder.title" name="title" placeholder="Work required" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm sm:col-span-2"><select [(ngModel)]="workOrder.priority" name="priority" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><option>low</option><option>medium</option><option>high</option><option>critical</option></select><input [(ngModel)]="workOrder.dueAt" name="dueAt" type="date" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><input [(ngModel)]="workOrder.cost" name="cost" type="number" min="0" placeholder="Estimated cost" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><button class="rounded bg-blue-500 px-3 py-2 text-xs font-bold text-white">Create work order</button></div></form>
          <form (ngSubmit)="savePlan()" class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase tracking-wider text-gray-400">Maintenance plan</h3><div class="mt-3 grid gap-2 sm:grid-cols-2"><input [(ngModel)]="plan.name" name="planName" placeholder="Plan name" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm sm:col-span-2"><input [(ngModel)]="plan.intervalDays" name="intervalDays" type="number" min="1" placeholder="Interval days" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><input [(ngModel)]="plan.intervalMeter" name="intervalMeter" type="number" min="1" placeholder="Meter interval" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><select [(ngModel)]="plan.meterType" name="planMeterType" class="rounded border border-gray-700 bg-gray-900 px-3 py-2 text-sm"><option [ngValue]="null">No meter</option><option value="odometer_km">Odometer</option><option value="engine_hours">Engine hours</option><option value="cycles">Cycles</option></select><button class="rounded bg-blue-500 px-3 py-2 text-xs font-bold text-white">Save plan</button></div></form>
          <div class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase tracking-wider text-gray-400">Return to service</h3><p class="mt-2 text-xs leading-5 text-gray-500">Maker-checker approval is required. High and critical work orders must be closed first.</p><button type="button" (click)="requestReturnToService()" class="mt-3 w-full rounded border border-emerald-800 px-3 py-2 text-xs font-bold uppercase text-emerald-300">Request approval</button></div>
        </div>
        <div class="grid gap-4 lg:grid-cols-3"><div class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase text-gray-400">Open work orders</h3><div class="mt-2 space-y-2"><div *ngFor="let order of workOrders()" class="rounded border border-gray-800 p-2 text-xs"><div class="flex justify-between"><b>{{ order.title }}</b><span>{{ order.priority }}</span></div><p class="text-gray-500">{{ order.status }} / R {{ order.cost | number:'1.0-2' }}</p><button *ngIf="order.status !== 'completed'" (click)="completeWorkOrder(order)" class="mt-1 text-emerald-300">Mark complete</button></div><p *ngIf="!workOrders().length" class="text-xs text-gray-600">None recorded.</p></div></div><div class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase text-gray-400">Compliance</h3><div class="mt-2 space-y-2"><div *ngFor="let item of complianceRecords()" class="rounded border border-gray-800 p-2 text-xs"><b>{{ item.complianceType }}</b><p [class.text-red-300]="item.status === 'expired'" [class.text-amber-300]="item.status === 'due'">{{ item.status }} / {{ item.expiresAt || 'No expiry' }}</p></div><p *ngIf="!complianceRecords().length" class="text-xs text-gray-600">None recorded.</p></div></div><div class="rounded-xl border border-gray-800 bg-gray-950 p-3"><h3 class="text-xs font-bold uppercase text-gray-400">Custody history</h3><div class="mt-2 space-y-2"><div *ngFor="let event of custodyEvents()" class="rounded border border-gray-800 p-2 text-xs"><b>{{ event.toCustodian || 'Unassigned' }}</b><p class="text-gray-500">{{ event.occurredAt | date:'short' }}</p></div><p *ngIf="!custodyEvents().length" class="text-xs text-gray-600">None recorded.</p></div></div></div>
      </div>
    </section>
  `,
})
export class AssetOperationsComponent {
  readonly service = inject(OfficeAdminService);
  readonly feedback = signal('');
  readonly transferReview = signal<AssignmentReview | null>(null);
  readonly transferReasonCode = signal('');
  private readonly selectedAssetId = signal('');
  @Input() set assetId(value: string) { this.selectedAssetId.set(value || ''); this.resetForms(value || ''); }
  readonly asset = computed(() => this.service.assets().find((entry) => entry.id === this.selectedAssetId()) || null);
  readonly workOrders = computed(() => this.service.assetWorkOrders().filter((entry) => entry.assetId === this.selectedAssetId()));
  readonly complianceRecords = computed(() => this.service.assetComplianceRecords().filter((entry) => entry.assetId === this.selectedAssetId()));
  readonly custodyEvents = computed(() => this.service.assetCustodyEvents().filter((entry) => entry.assetId === this.selectedAssetId()));
  readonly fuelEntries = computed(() => this.service.assetFuelEntries().filter((entry) => entry.assetId === this.selectedAssetId()));
  transferSiteId = ''; transferCustodian = ''; transferNotes = '';
  compliance!: AssetComplianceRecord; meter!: AssetMeterReading; workOrder!: AssetWorkOrder; plan!: AssetMaintenancePlan;
  fuel!: Omit<AssetFuelEntry, 'id' | 'organizationId' | 'totalCost' | 'recordedBy' | 'createdAt'>;
  constructor() { this.resetForms(''); }
  private resetForms(assetId: string) {
    this.transferSiteId = this.asset()?.assignedSiteId || ''; this.transferCustodian = this.asset()?.custodianName || ''; this.transferNotes = '';
    this.transferReview.set(null); this.transferReasonCode.set('');
    this.compliance = { id: '', organizationId: SENATLA_TRADING_ORGANIZATION_ID, assetId, complianceType: 'inspection', status: 'valid', issuedAt: null, expiresAt: null };
    this.meter = { id: '', organizationId: SENATLA_TRADING_ORGANIZATION_ID, assetId, meterType: 'engine_hours', reading: 0, recordedAt: new Date().toISOString(), recordedBy: '', source: 'manual' };
    this.fuel = { assetId, fuelDate: new Date().toISOString().slice(0, 10), litres: 0, unitCost: 0, odometerKm: null, engineHours: null, supplier: '', referenceNumber: '' };
    this.workOrder = { id: '', organizationId: SENATLA_TRADING_ORGANIZATION_ID, assetId, title: '', status: 'open', priority: 'medium', dueAt: null, completedAt: null, cost: 0 };
    this.plan = { id: '', organizationId: SENATLA_TRADING_ORGANIZATION_ID, assetId, name: '', intervalDays: null, intervalMeter: null, meterType: null, nextDueAt: null, nextDueMeter: null, isActive: true };
  }
  private async run(action: () => Promise<unknown>, success: string) { try { this.feedback.set(''); await action(); this.feedback.set(success); } catch (error) { this.feedback.set(error instanceof Error ? error.message : 'Action failed.'); } }
  reviewTransfer() { this.feedback.set(''); this.transferReasonCode.set(''); this.transferReview.set(this.service.reviewAssetSiteTransfer(this.selectedAssetId(), this.transferSiteId)); }
  transfer(decision: AssignmentDecision) { return this.run(async () => { await this.service.transferAsset(this.selectedAssetId(), this.transferSiteId, this.transferCustodian, this.transferNotes, decision, this.transferReasonCode()); this.transferReview.set(null); this.transferReasonCode.set(''); }, decision === 'reject' ? 'Transfer suggestion rejected and audited.' : 'Custody transfer recorded and audited.'); }
  saveCompliance() { return this.run(() => this.service.saveComplianceRecord(this.compliance), 'Compliance record saved.'); }
  recordMeter() { return this.run(() => this.service.recordMeterReading(this.meter), 'Meter reading recorded.'); }
  saveFuel() { return this.run(async () => { await this.service.saveFuelEntry(this.fuel); this.resetForms(this.selectedAssetId()); }, 'Fuel expense recorded.'); }
  saveWorkOrder() { return this.run(async () => { await this.service.saveWorkOrder(this.workOrder); this.resetForms(this.selectedAssetId()); }, 'Work order created.'); }
  savePlan() { return this.run(async () => { await this.service.saveMaintenancePlan(this.plan); this.resetForms(this.selectedAssetId()); }, 'Maintenance plan saved.'); }
  completeWorkOrder(order: AssetWorkOrder) { return this.run(() => this.service.saveWorkOrder({ ...order, status: 'completed' }), 'Work order completed.'); }
  requestReturnToService() { return this.run(() => this.service.submitApprovalRequest('asset_return_to_service', { assetId: this.selectedAssetId() }), 'Return-to-service request submitted for approval.'); }
}
