export const SENATLA_DOCUMENT_SCANNER_PLUGIN = 'SenatlaDocumentScanner' as const;

export const SCAN_LIMITS = {
  minPages: 1,
  maxPages: 5,
  minDimensionPixels: 32,
  maxDimensionPixels: 10_000,
  maxArtifactBytes: 15 * 1024 * 1024,
  maxTextCharacters: 100_000,
  maxTextBlocks: 5_000,
  maxRecognitionLanguages: 8,
} as const;

export type ScanErrorCode =
  | 'UNSUPPORTED_PLATFORM'
  | 'INVALID_OPTIONS'
  | 'USER_CANCELLED'
  | 'PERMISSION_DENIED'
  | 'NATIVE_FAILURE'
  | 'MALFORMED_RESULT'
  | 'ARTIFACT_FETCH_FAILED'
  | 'ARTIFACT_TOO_LARGE'
  | 'ARTIFACT_INTEGRITY_FAILED'
  | 'CLEANUP_FAILED';

const SAFE_ERROR_MESSAGES: Record<ScanErrorCode, string> = {
  UNSUPPORTED_PLATFORM: 'Document scanning is not available on this device.',
  INVALID_OPTIONS: 'The document scan request is invalid.',
  USER_CANCELLED: 'Document scanning was cancelled.',
  PERMISSION_DENIED: 'Camera permission is required to scan a document.',
  NATIVE_FAILURE: 'The device could not complete the document scan.',
  MALFORMED_RESULT: 'The device returned an invalid document scan result.',
  ARTIFACT_FETCH_FAILED: 'The scanned document could not be read securely.',
  ARTIFACT_TOO_LARGE: 'The scanned document exceeds the allowed size.',
  ARTIFACT_INTEGRITY_FAILED: 'The scanned document failed its integrity check.',
  CLEANUP_FAILED: 'Temporary scan files could not be removed securely.',
};

export class ScanError extends Error {
  constructor(readonly code: ScanErrorCode) {
    super(SAFE_ERROR_MESSAGES[code]);
    this.name = 'ScanError';
  }
}

export interface ScannerAvailability {
  available: boolean;
  reason?: 'unsupported_platform' | 'camera_unavailable' | 'service_unavailable';
}

export interface ScanOptions {
  /** UUID generated by the caller and echoed by the native implementation. */
  sessionId: string;
  maxPages: number;
  galleryImportAllowed: boolean;
  /** Ordered BCP-47 language hints. Native implementations may use a supported subset. */
  recognitionLanguages: string[];
}

export interface ScanBounds {
  /** Coordinates normalized to the page, in the inclusive range 0..1. */
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface ScanTextBlock {
  text: string;
  confidence?: number;
  bounds?: ScanBounds;
}

export interface ScanPage {
  /** UUID identifier; it must not contain a filesystem path or user-entered text. */
  artifactId: string;
  /** Temporary native file URI. Data URLs and remote URLs are forbidden. */
  uri: string;
  mimeType: 'image/jpeg';
  byteSize: number;
  width: number;
  height: number;
  sha256: string;
  text: string;
  textBlocks: ScanTextBlock[];
}

export interface ScanResult {
  sessionId: string;
  pages: ScanPage[];
}

export interface ReleaseScanOptions {
  sessionId: string;
  artifactIds?: string[];
}

export interface SenatlaDocumentScannerPlugin {
  isAvailable(): Promise<ScannerAvailability>;
  scan(options: ScanOptions): Promise<ScanResult>;
  release(options: ReleaseScanOptions): Promise<void>;
}

export interface NormalizedOcrResult {
  text: string;
  textBlocks: ScanTextBlock[];
  recognitionLanguages: string[];
}

export interface AssetEvidenceScan {
  sessionId: string;
  artifactId: string;
  file: File;
  width: number;
  height: number;
  sha256: string;
  ocr: NormalizedOcrResult;
}
